name: Build FreeCAD documents

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build files
        uses: Gigahawk/freecad-export-action@master
        with:
          paths: |
            SW_Cherry_MX_PCB.FCStd
            Stabilizer_Cherry_MX_2u.FCStd
            kicad_proj/kicad_proj.kicad_pcb
          output-path: export
          export-types: |
            step
            wrl
            stl

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: export
          path: export/